### ISSUE TITLE
Create Fields Demo! 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields-demo#2]
Create a super basic app that allows people to register for a fictitious event called "**_Awesome_ Conf**"!

# Todo

+ [ ] Use as many of the `fields` as possible and showcase how the data is stored (encrypted).
+ [ ] Create Two Buttons to automatically input data into the form:
  + [ ] 
  + [ ] 
+ [ ] Show the data that has been submitted
+ [ ] Show what the encrypted data looks like in the Database

**Comment by nelsonic** [comment]
The _reason_ I'm working on this _now_ is: https://github.com/dwyl/fields/pull/150 ⏳

**Comment by nelsonic** [comment]
These are the fields I'm thinking of including:

+ First Name
+ Last Name
+ Email
+ Gender
+ Phone Number
+ Dietary preference
+ Brief Description of your Awesome Project
+ Personal/Company Website showcasing your awesomeness: 
+ Address (where we will send your welcome pack)
+ Postcode
+ Feedback / Suggestions

Trying to use as many of `Fields` as possible:

<img width="920" alt="image" src="https://github.com/dwyl/fields-demo/assets/194400/c0a113b3-01bb-47d7-a61d-0f97298b1221">

We can always add more later. 💭

**Comment by nelsonic** [comment]
BRB. Gotta go sleep for a bit. 🛌

**Comment by nelsonic** [comment]
![awesome-header-image](https://github.com/dwyl/fields-demo/assets/194400/a87a35ab-409d-4204-8b9f-8d4725b505f0)

**Comment by nelsonic** [comment]
Gonna create this using `CSS` (`Tailwind`) as part of the tutorial. 💭 
Here's the background I'm thinking of using: 

![image](https://github.com/dwyl/fields-demo/assets/194400/7030bbd8-372b-425a-ab3c-ab961bf74d5a)

Via: https://www.deviantart.com/raindroplover/art/Rainbow-Explosion-in-Acrylic-Paint-734939310
